// src/utils/stateList.js

export const STATES = {
  'India': [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
  ],
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  'Poland': [
    'Lower Silesian Voivodeship',
    'Kuyavian-Pomeranian Voivodeship',
    'Lublin Voivodeship',
    'Lubusz Voivodeship',
    'Łódź Voivodeship',
    'Lesser Poland Voivodeship',
    'Masovian Voivodeship',
    'Opole Voivodeship',
    'Subcarpathian Voivodeship',
    'Podlaskie Voivodeship',
    'Pomeranian Voivodeship',
    'Silesian Voivodeship',
    'Holy Cross Voivodeship',
    'Warmian-Masurian Voivodeship',
    'Greater Poland Voivodeship',
    'West Pomeranian Voivodeship',
  ],
  'United Kingdom': ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  'Spain': [
    'Andalusia',
    'Aragon',
    'Principality of Asturias',
    'Balearic Islands',
    'Basque Country',
    'Canary Islands',
    'Cantabria',
    'Castile and León',
    'Castile-La Mancha',
    'Catalonia',
    'Extremadura',
    'Galicia',
    'Community of Madrid',
    'Region of Murcia',
    'Foral Community of Navarre',
    'La Rioja',
    'Valencian Community',
    'Ceuta',
    'Melilla',
  ],
  'Portugal': [
    'Aveiro',
    'Beja',
    'Braga',
    'Bragança',
    'Castelo Branco',
    'Coimbra',
    'Évora',
    'Faro',
    'Guarda',
    'Leiria',
    'Lisbon',
    'Portalegre',
    'Porto',
    'Santarém',
    'Setúbal',
    'Viana do Castelo',
    'Vila Real',
    'Viseu',
    'Madeira',
    'Azores',
  ],
  'Canada': [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon',
    'Northwest Territories',
    'Nunavut',
  ],
  'Ukraine': [
    'Cherkasy Oblast',
    'Chernihiv Oblast',
    'Chernivtsi Oblast',
    'Dnipropetrovsk Oblast',
    'Donetsk Oblast',
    'Ivano-Frankivsk Oblast',
    'Kharkiv Oblast',
    'Kherson Oblast',
    'Khmelnytskyi Oblast',
    'Kirovohrad Oblast',
    'Kyiv Oblast',
    'Luhansk Oblast',
    'Lviv Oblast',
    'Mykolaiv Oblast',
    'Odesa Oblast',
    'Poltava Oblast',
    'Rivne Oblast',
    'Sumy Oblast',
    'Ternopil Oblast',
    'Vinnytsia Oblast',
    'Volyn Oblast',
    'Zakarpattia Oblast',
    'Zaporizhzhia Oblast',
    'Zhytomyr Oblast',
    'Autonomous Republic of Crimea',
    'City of Kyiv',
    'City of Sevastopol',
  ],
  'France': [
    'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté',
    'Brittany',
    'Centre-Val de Loire',
    'Corsica',
    'Grand Est',
    'Hauts-de-France',
    'Île-de-France',
    'Normandy',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Pays de la Loire',
    "Provence-Alpes-Côte d'Azur",
    'French Guiana',
    'Guadeloupe',
    'Martinique',
    'Mayotte',
    'Réunion',
  ],
  'Russia': [
    'Republic of Adygea',
    'Altai Republic',
    'Republic of Bashkortostan',
    'Republic of Buryatia',
    'Republic of Dagestan',
    'Republic of Ingushetia',
    'Kabardino-Balkarian Republic',
    'Republic of Kalmykia',
    'Karachay-Cherkess Republic',
    'Republic of Karelia',
    'Komi Republic',
    'Republic of Crimea',
    'Mari El Republic',
    'Republic of Mordovia',
    'Sakha (Yakutia) Republic',
    'Republic of North Ossetia–Alania',
    'Republic of Tatarstan',
    'Republic of Tuva',
    'Udmurt Republic',
    'Republic of Khakassia',
    'Chechen Republic',
    'Chuvash Republic',
    'Altai Krai',
    'Kamchatka Krai',
    'Khabarovsk Krai',
    'Krasnodar Krai',
    'Krasnoyarsk Krai',
    'Perm Krai',
    'Primorsky Krai',
    'Stavropol Krai',
    'Transbaikal Krai',
    'Amur Oblast',
    'Arkhangelsk Oblast',
    'Astrakhan Oblast',
    'Belgorod Oblast',
    'Bryansk Oblast',
    'Chelyabinsk Oblast',
    'Irkutsk Oblast',
    'Ivanovo Oblast',
    'Kaliningrad Oblast',
    'Kaluga Oblast',
    'Kemerovo Oblast–Kuzbass',
    'Kirov Oblast',
    'Kostroma Oblast',
    'Kurgan Oblast',
    'Kursk Oblast',
    'Leningrad Oblast',
    'Lipetsk Oblast',
    'Magadan Oblast',
    'Moscow Oblast',
    'Murmansk Oblast',
    'Nizhny Novgorod Oblast',
    'Novgorod Oblast',
    'Novosibirsk Oblast',
    'Omsk Oblast',
    'Orenburg Oblast',
    'Oryol Oblast',
    'Penza Oblast',
    'Pskov Oblast',
    'Rostov Oblast',
    'Ryazan Oblast',
    'Sakhalin Oblast',
    'Samara Oblast',
    'Saratov Oblast',
    'Smolensk Oblast',
    'Sverdlovsk Oblast',
    'Tambov Oblast',
    'Tomsk Oblast',
    'Tula Oblast',
    'Tver Oblast',
    'Tyumen Oblast',
    'Ulyanovsk Oblast',
    'Vladimir Oblast',
    'Volgograd Oblast',
    'Vologda Oblast',
    'Voronezh Oblast',
    'Yaroslavl Oblast',
    'Moscow (federal city)',
    'Saint Petersburg (federal city)',
    'Sevastopol (federal city)',
    'Jewish Autonomous Oblast',
    'Chukotka Autonomous Okrug',
    'Khanty-Mansi Autonomous Okrug – Yugra',
    'Nenets Autonomous Okrug',
    'Yamalo-Nenets Autonomous Okrug',
    'Kherson Oblast (disputed)',
    'Zaporizhzhia Oblast (disputed)',
    "Donetsk People's Republic (disputed)",
    "Luhansk People's Republic (disputed)",
  ],
};
